language: node_js

os: windows

node_js:
  - "16.x"

install:
  - 'npm install'

services:
  - mongodb

cache:
  npm: false

notifications:
  email: false

script:
  - npm ci
  - npm test
  - npm run coverage

after_success:
  - npm run coveralls
