language: node_js

node_js:
  - 16

env:
  PORT: 8080

install:
  - 'npm install'

services:
  - mongodb

cache:
  npm: false

notifications:
  email: false

script:
  - npm ci
  - npm run coverage

after_success:
  - npm run coveralls
